python .\auto_score_counter.py --img_path .\data\scores\001.png
python .\auto_score_counter.py --img_path .\data\scores\002.png
python .\auto_score_counter.py --img_path .\data\scores\003.png
python .\auto_score_counter.py --img_path .\data\scores\004.png
python .\auto_score_counter.py --img_path .\data\scores\005.png
python .\auto_score_counter.py --img_path .\data\scores\006.png
python .\auto_score_counter.py --img_path .\data\scores\007.png
python .\auto_score_counter.py --img_path .\data\scores\008.png
python .\auto_score_counter.py --img_path .\data\scores\009.png
python .\auto_score_counter.py --img_path .\data\scores\010.png
python .\auto_score_counter.py --img_path .\data\scores\011.png
python .\auto_score_counter.py --img_path .\data\scores\012.png
